server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sales
    username: user
    password: pass

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update